plugins{
    id 'library.deps-conventions'
    id 'library.java-conventions'
    id 'library.jdeps-conventions'

    // The following plugin is used to build the OSGI bundle
    id 'biz.aQute.bnd.builder' version '6.4.0'
}

configurations {
    windows_x64
    wrimsCore
    api.extendsFrom(wrimsCore)
}

def osgiPlatform = 'win32.win32.x86_64'

dependencies {
    api platform(libs.wrims.engine.bom)
    wrimsCore libs.wrims.core

    implementation libs.eclipse.core.runtime
    implementation libs.eclipse.debug.core
    implementation(libs.eclipse.swt) {
        exclude group: "org.eclipse.platform", module: "org.eclipse.swt"
    }
    implementation(libs.eclipse.debug.ui) {
        exclude group: "org.eclipse.platform", module: "org.eclipse.swt"
    }
    implementation libs.eclipse.datatools.connectivity

    implementation project(':third-party')

    windows_x64(libs.javaHeclib){artifact {type = 'zip'}}
    testImplementation(libs.bundles.junit5)
}

configurations.configureEach {
    exclude group: "javax.media", module: "jai_core"
    exclude group: "javax.media", module: "jai_codec"
    exclude group: "com.sun.media", module: "jai_imageio"
}

tasks.register('copyWrimsCore', Copy) {
    from({configurations.wrimsCore.copy().setTransitive(false)})
    into layout.buildDirectory.dir('tmp/wrims-core')
    rename { String fileName -> 'wrims-core.jar' }
}

//task to download native libraries (dlls)
tasks.register('getNatives', Sync) { syncTask ->
    syncTask.from configurations.windows_x64.collect { zipTree(it) }
    syncTask.into file("${layout.buildDirectory.asFile.get()}/lib")
}

test {
    useJUnitPlatform()
    dependsOn(getNatives)
    systemProperty "java.library.path", "${layout.buildDirectory.asFile.get()}/lib"
}

jar {
    dependsOn tasks.named('copyWrimsCore')

    bundle {
        // Ensure classpath is ready before bundling
        dependsOn(configurations.runtimeClasspath)
    }
}