plugins{
    id 'library.deps-conventions'
    id 'library.java-conventions'
    id 'library.jdeps-conventions'

    // The following plugin is used to build the OSGI bundle
    id 'biz.aQute.bnd.builder' version '7.2.3'
}

configurations {
    windows_x64
    wrimsCore
    api.extendsFrom(wrimsCore)
}

dependencies {
    api platform(libs.wrims.engine.bom)
    wrimsCore libs.wrims.core

    implementation libs.eclipse.core.runtime
    implementation libs.eclipse.debug.core
    implementation(libs.eclipse.swt) {
        exclude group: "org.eclipse.platform", module: "org.eclipse.swt"
    }
    implementation(libs.eclipse.debug.ui) {
        exclude group: "org.eclipse.platform", module: "org.eclipse.swt"
    }
    implementation libs.eclipse.datatools.connectivity

    implementation project(':third-party')

    windows_x64(libs.javaHeclib){artifact {type = 'zip'}}
    testImplementation(libs.bundles.junit5)

    // GraalPy
    implementation libs.bundles.graalvm.bnd
}

configurations.configureEach {
    exclude group: "javax.media", module: "jai_core"
    exclude group: "javax.media", module: "jai_codec"
    exclude group: "com.sun.media", module: "jai_imageio"
}

tasks.register('copyWrimsCore', Copy) {
    from({configurations.wrimsCore.copy().setTransitive(false)})
    into layout.buildDirectory.dir('tmp/wrims-core')
    rename { String fileName -> 'wrims-core.jar' }
}

//task to download native libraries (dlls)
tasks.register('getNatives', Sync) { syncTask ->
    syncTask.from configurations.windows_x64.collect { zipTree(it) }
    syncTask.into file("${layout.buildDirectory.asFile.get()}/lib")
}

test {
    dependsOn(getNatives)
    systemProperty "java.library.path", "${layout.buildDirectory.asFile.get()}/lib"
}

// Task to copy GraalPy JARs
tasks.register('copyGraalPy', Copy) {
    from configurations.runtimeClasspath
    include "polyglot-*.jar"
    include "python-*.jar"
    include "icu4j-*.jar"
    include "truffle-api-*.jar"
    include "graal-*.jar"
    include "svm-*.jar"
    include "truffle-*.jar"
    include "compiler-*.jar"
    include "collections-*.jar"
    include "word-*.jar"
    include "xz-*.jar"
    include "native-image-base-*.jar"
    include "nativeimage-*.jar"
    include "espresso-*.jar"
    include "graalvm-*.jar"
    into layout.buildDirectory.dir('tmp/graalpy')
    duplicatesStrategy DuplicatesStrategy.EXCLUDE
    rename { fileName ->
        if (fileName.startsWith('polyglot-')) return 'graalvm-polyglot.jar'
        if (fileName.startsWith('python-embedding-')) return 'graalvm-python-embedding.jar'
        if (fileName.startsWith('python-language-')) return 'graalvm-python-language.jar'
        if (fileName.startsWith('python-resources-')) return 'graalvm-python-resources.jar'
        if (fileName.startsWith('graal-sdk-')) return 'graalvm-sdk.jar'
        if (fileName.startsWith('compiler-')) return 'graalvm-compiler.jar'
        if (fileName.startsWith('collections-')) return 'graalvm-collections.jar'
        if (fileName.startsWith('espresso-svm-')) return 'graalvm-espresso-svm.jar'
        if (fileName.startsWith('json-')) return 'graalvm-json.jar'
        if (fileName.startsWith('library-support-')) return 'graalvm-library-support.jar'
        if (fileName.startsWith('nativeimage-')) return 'graalvm-native-image.jar'
        if (fileName.startsWith('native-image-base-')) return 'graalvm-native-image-base.jar'
        if (fileName.startsWith('objectfile-')) return 'graalvm-objectfile.jar'
        if (fileName.startsWith('pointsto-')) return 'graalvm-pointsto.jar'
        if (fileName.startsWith('profiler-tool-')) return 'graalvm-profiler-tool.jar'
        if (fileName.startsWith('python-language-')) return 'graalvm-python-language.jar'
        if (fileName.startsWith('regex-')) return 'graalvm-regex.jar'
        if (fileName.startsWith('svm-')) return 'graalvm-svm.jar'
        if (fileName.startsWith('svm-capnproto-runtime-')) return 'graalvm-svm-runtime.jar'
        if (fileName.startsWith('svm-configure-')) return 'graalvm-svm-configure.jar'
        if (fileName.startsWith('truffle-api-')) return 'graalvm-truffle-api.jar'
        if (fileName.startsWith('truffle-compiler-')) return 'graalvm-truffle-compiler.jar'
        if (fileName.startsWith('truffle-runtime-')) return 'graalvm-truffle-runtime.jar'
        if (fileName.startsWith('word-')) return 'graalvm-word.jar'
        if (fileName.startsWith('xz-')) return 'graalvm-xz.jar'
        return fileName
    }
}

jar {
    dependsOn tasks.named('copyWrimsCore')
    dependsOn tasks.named('copyGraalPy')

    bundle {
        // Ensure classpath is ready before bundling
        dependsOn(configurations.runtimeClasspath)
    }
}
