package gov.ca.water.wrims.gui.ide.wsidi;

import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import java.nio.file.Paths;
import java.util.ArrayList;
import java.util.List;

import com.google.common.flogger.FluentLogger;
import gov.ca.water.wrims.engine.core.components.ControllerBatch;
import gov.ca.water.wrims.gui.ide.debugger.exception.WPPException;
import gov.ca.water.wrims.gui.ide.debugger.launcher.WPPSettings;

public final class RunEngine {
	private static final FluentLogger logger = FluentLogger.forEnclosingClass();
	private static final String JRE_PLUGIN_PREFIX_DEFAULT = "org.eclipse.justj.openjdk.hotspot.jre.full";
	private static final int MAX_HEAP_SIZE_DEFAULT = 4096; // Default heap size in MB
	private static final int STACK_SIZE_DEFAULT = 1024; // Default stack size in KB
	private static final String TIMEZONE_DEFAULT = "UTC";
	private static final String NAME_DEFAULT = "51677";

	public static final String JRE_PLUGIN_KEY = "gov.ca.water.wrims.jre.plugin.prefix";
	public static final String WSIDI_GEN_MAX_HEAP_SIZE_KEY = "gov.ca.water.wrims.wsidi.gen.max.heap.size";
	public static final String WSIDI_GEN_STACK_SIZE_KEY = "gov.ca.water.wrims.wsidi.gen.stack.size";
	public static final String WSIDI_GEN_TIMEZONE_KEY = "gov.ca.water.wrims.wsidi.gen.timezone";
	public static final String WSIDI_GEN_NAME_KEY = "gov.ca.water.wrims.wsidi.gen.name";

	private static final String JRE_PLUGIN_PREFIX = System.getProperty(JRE_PLUGIN_KEY, JRE_PLUGIN_PREFIX_DEFAULT);
	private static final int MAX_HEAP_SIZE = Integer.parseInt(System.getProperty(WSIDI_GEN_MAX_HEAP_SIZE_KEY, String.valueOf(MAX_HEAP_SIZE_DEFAULT)));
	private static final int STACK_SIZE = Integer.parseInt(System.getProperty(WSIDI_GEN_STACK_SIZE_KEY, String.valueOf(STACK_SIZE_DEFAULT)));
	private static final String TIMEZONE = System.getProperty(WSIDI_GEN_TIMEZONE_KEY, TIMEZONE_DEFAULT);
	private static final String NAME = System.getProperty(WSIDI_GEN_NAME_KEY, NAME_DEFAULT);

	private final String externalPath;
	private final String configFilePath;

	public RunEngine(String externalPath, String configFilePath) {
		this.externalPath = externalPath;
		this.configFilePath = configFilePath;
	}

	public void execute() throws IOException {
		List<String> command = buildCommand();

		writeToFile(command);

		ProcessBuilder processBuilder = new ProcessBuilder();
		String systemRoot = System.getenv("SystemRoot");
		String cmdExe = Paths.get(systemRoot, "System32", "cmd.exe").toString();
		processBuilder.command(cmdExe, "/c", "start", "/wait", WPPSettings.WRIMS_ENGINE_BAT);

		Process process = processBuilder.start();

		// Optionally wait for process completion
		try {
			int exitCode = process.waitFor();
			if (exitCode != 0) {
				logger.atSevere().log("WRIMS engine execution failed with exit code: %s", exitCode);
			}
		} catch (InterruptedException e) {
			Thread.currentThread().interrupt();
			throw new RuntimeException("Process was interrupted", e);
		}
	}

	private void writeToFile(List<String> command) {
		try(FileWriter fw = new FileWriter(WPPSettings.WRIMS_ENGINE_BAT);
			PrintWriter out = new PrintWriter(fw)) {
			out.println("@echo off");
			out.println();
			out.println("set path=" + externalPath + ";lib;%path%");
			out.println();
			out.println("REM This script is generated by WRIMS for WSIDI Generation. Direct edits may be overwritten.");
			out.println();

			String commandLine = String.join(" ", command);
			out.println(commandLine);

			logger.atConfig().log("Batch file written to: %s", WPPSettings.WRIMS_ENGINE_BAT);
		} catch(IOException e) {
			logger.atWarning().log("Failed to write batch file: %s", e.getMessage());
			WPPException.handleException(e);
		}
	}

	private List<String> buildCommand() {
		List<String> command = new ArrayList<>();

		// Java executable
		String jrePluginFolder = findJrePluginFolder();
		command.add("plugins\\" + jrePluginFolder + "\\jre\\bin\\java");

		// JVM arguments
		command.add("-Xmx" + MAX_HEAP_SIZE + "m");
		command.add("-Xss" + STACK_SIZE + "K");
		command.add("-Duser.timezone=" + TIMEZONE);
		command.add("-XX:+CreateMinidumpOnCrash");
		command.add("-Dname=" + NAME);

		// Library path
		String libraryPath = sanitize(externalPath + ";lib");
		command.add(String.format("-Djava.library.path=\"%s\"", libraryPath));
		logger.atFiner().log("Library path: %s", libraryPath);

		// Classpath
		command.add("-cp");
		String classpath = sanitize(String.format("\"%s/*;lib/*\"", externalPath));
		command.add(classpath);
		logger.atFiner().log("Classpath: %s", classpath);

		// Main class and arguments
		command.add(ControllerBatch.class.getCanonicalName());
		command.add("-config=" + sanitize(configFilePath));

		logger.atFiner().log("Executing command: %s", command);

		return command;
	}

	private String findJrePluginFolder() {
		String pluginsPath = "plugins";
		File pluginsDir = new File(pluginsPath);
		if(!pluginsDir.exists() || !pluginsDir.isDirectory()) {
			logger.atWarning().log("Plugins directory not found: %s", pluginsPath);
			return null;
		}

		File[] directories = pluginsDir.listFiles(File::isDirectory);
		if(directories == null) {
			logger.atWarning().log("Failed to list directories in: %s", pluginsPath);
			return null;
		}

		for(File dir : directories) {
			if(dir.getName().startsWith(JRE_PLUGIN_PREFIX)) {
				logger.atFiner().log("Found JRE plugin folder: %s", dir.getName());
				return dir.getName();
			}
		}

		logger.atWarning().log("JRE plugin folder with prefix '%s' not found in: %s", JRE_PLUGIN_PREFIX, pluginsPath);
		return null;
	}

	private String sanitize(String input) {
		StringBuilder commandLine = new StringBuilder();
		if(input.contains(" ") && !input.startsWith("\"")) {
			commandLine.append("\"").append(input).append("\"");
		} else {
			commandLine.append(input);
		}
		return commandLine.toString();
	}
}
