// This is the root build.gradle, which defines a few project-wide properties.
// Notably, this project sets the version of all projects, as well as the group name.

plugins {
    id "com.palantir.git-version" version "3.0.0"
    id 'base'
    id 'eclipse'
    id 'org.sonarqube' version '6.3.1.5724'
    id 'library.deps-conventions'
    id 'jacoco'
}

allprojects {
    apply plugin: 'eclipse'
}

// This utilizes Git Tag based versioning to set the version of the project based on the current Git Branch or Tag.
// If a tag is checked out, the version will be the name of the most recent tag on this commit.
// Otherwise, the version will be last version suffixed with a +
def versionLabel(gitInfo) {
    def branch = gitInfo.branchName // all branches are snapshots, only tags get released
    def tag = gitInfo.lastTag
    def defaultVersion = tag + ".9999"
    def isNumericTag = gitInfo.lastTag ==~ /^\d+\.\d+\.\d+.*/
    if(!isNumericTag) {
        defaultVersion = "1.0.0.9999"
    }
    // tag is returned as is. Branch may need cleanup
    return branch == null ? tag : defaultVersion
}

sonar {
    properties {
        property "sonar.projectKey", "CentralValleyModeling_wrims-gui"
        property "sonar.organization", "dwr-cvm"
        property "sonar.host.url", "https://sonarcloud.io"
        property "sonar.pullrequest.provider", "GitHub"
        property "sonar.pullrequest.github.repository", "CentralValleyModeling/wrims-gui"
        property "sonar.coverage.jacoco.xmlReportPaths", "$rootDir/wrims-ide/build/reports/jacoco/test/jacocoTestReport.xml"
    }
}

allprojects {
    group = 'gov.ca.water'
    version = versionLabel(versionDetails())
}

// Define the aggregation task to merge reports from all subprojects
tasks.register('codeCoverageReport', JacocoReport) {
    group = 'Verification'
    description = 'Generates an aggregate code coverage report for all subprojects'

    subprojects { subproject ->
        subproject.plugins.withType(JacocoPlugin).each {
            subproject.tasks.matching({t -> t.extensions.findByType(JacocoTaskExtension)}).each { testTask ->
                if(testTask.extensions.getByType(JacocoTaskExtension).isEnabled()) {
                    sourceSets subproject.sourceSets.main
                    executionData(testTask)
                }
            }
        }
    }

    reports {
        xml.required = true
        html.required = false
        csv.required = false
    }

    classDirectories.setFrom(files(classDirectories.files.collect {
        fileTree(dir: it)
    }))
}

subprojects {
    sonar {
        properties {
            property "sonar.coverage.jacoco.xmlReportPaths", "$rootDir/build/reports/jacoco/codeCoverageReport/codeCoverageReport.xml"
        }
    }
}
