[versions]
wrims-engine = "3.0.0-alpha.4"
commons-io = "2.20.0"
junit_5 = "5.11.3"
antlr = "3.5.2"
itext = "2009.09.21"
jfreechart = "1.5.6"
osgi_core = "6.0.0"
osgi_compendium = "5.0.0"
slf4jnop = "2.0.17"
guice = "7.0.0"
log4j = "1.2.17"
mssql_jdbc = "13.2.1.jre11"
hec-monolith = "6.0.0"
dssgui = "3.4.18"
javaHeclib = "7-IU-4-win-x86_64"
antlr-generator = "3.2.1"
coinor = "2021.12.17"
dsm2-input-model = "2010.03.15"
jpy = "2010.01.17"
jpython = "1998.10.30"
mssql-jdbc = "13.2.0.jre11"
swixml = "2007.03.28"
jdiagram = "4.3.1"
hdf = "2.10.0"
hdf5 = "2.10.0"
x64-dll = "2.2.0"
vista = "2014.05.20"
eclipse-core = "3.33.100"
eclipse-swt = "3.130.0"
eclipse-compare = "3.11.400"
eclipse-debug-core = "3.23.0"
eclipse-debug-ui = "3.18.800"
eclipse-datatools-connectivity = "1.15.0"
eclipse-ui = "3.207.200"
eclipse-jface = "3.37.0"
eclipse-jface-text = "3.28.0"
eclipse-osgi = "3.23.100"
eclipse-core-resources = "3.22.200"
eclipse-ui-views = "3.12.600"
eclipse-search = "3.17.200"
eclipse-xtext = "2.39.0"
eclipse-xtext-ui = "2.10.0"
eclipse-emf-edit = "2.23.0"
eclipse-emf-edit-ui = "2.26.0"
eclipse-ltk-core-refactoring = "3.15.0"

jaxb-api = "2.3.1"
jaxb-core = "2.3.0.1"
jaxb-impl = "2.3.2"
javax-activation = "1.1.1"

[libraries]
wrims-core = { module = "gov.ca.dwr:wrims-core", version.ref = "wrims-engine" }
wrims-engine-bom = { module = "gov.ca.dwr:wrims-engine-bom", version.ref = "wrims-engine" }
hec-monolith = { module = "mil.army.usace.hec:hec-monolith", version.ref = "hec-monolith" }
dssgui = { module = "mil.army.usace.hec:dssgui", version.ref = "dssgui" }
commons-io = { module = "commons-io:commons-io", version.ref = "commons-io" }
junit-5-engine = { module = "org.junit.jupiter:junit-jupiter-engine", version.ref = "junit_5" }
junit-5-api = { module = "org.junit.jupiter:junit-jupiter-api", version.ref = "junit_5" }
junit-5-params = { module = "org.junit.jupiter:junit-jupiter-params", version.ref = "junit_5" }
antlr = { module = "org.antlr:antlr", version.ref = "antlr" }
antlr-runtime = { module = "org.antlr:antlr-runtime", version.ref = "antlr" }
jfreechart = { module = "org.jfree:jfreechart", version.ref = "jfreechart" }
osgi-core = { module = "org.osgi:org.osgi.core", version.ref = "osgi_core" }
osgi-compendium = { module = "org.osgi:org.osgi.compendium", version.ref = "osgi_compendium" }
slf4jnop = { module = "org.slf4j:slf4j-nop", version.ref = "slf4jnop" }
guice = { module = "com.google.inject:guice", version.ref = "guice" }
log4j = { module = "log4j:log4j", version.ref = "log4j" }
mssql-jdbc = { module = "com.microsoft.sqlserver:mssql-jdbc", version.ref = "mssql_jdbc" }
javaHeclib = { module = "mil.army.usace.hec:javaHeclib", version.ref = "javaHeclib" }
itext = { module = "com.lowagie:itext", version.ref = "itext" }
antlr-generator = { module = "org.xtext:antlr-generator", version.ref = "antlr-generator" }

coinor = { module = "org.coinor:coinor", version.ref = "coinor" }
dsm2-input-model = { module = "gov.ca.dsm2:dsm2-input-model", version.ref = "dsm2-input-model" }
jpy = { module = "org.jpy:jpy", version.ref = "jpy" }
jpython = { module = "org.jpython:jpython", version.ref = "jpython" }
swixml = { module = "org.swixml:swixml", version.ref = "swixml" }
jdiagram = { module = "com.mindfusion:jdiagram", version.ref = "jdiagram" }
jarh5obj = { module = "ncsa.hdf:jarh5obj", version.ref = "hdf5" }
jarhdf5 = { module = "ncsa.hdf:jarhdf5", version.ref = "hdf5" }
jarhdfobj = { module = "ncsa.hdf:jarhdfobj", version.ref = "hdf" }
jarhdf = { module = "ncsa.hdf:jarhdf", version.ref = "hdf" }
vista = { module = "gov.ca.dwr:vista", version.ref = "vista" }

guava = { module = "com.google.guava:guava"}
kryo = { module = "com.esotericsoftware.kryo:kryo"}
linearsolver = { module = "com.google.ortools:linearsolver"}
calsurrogate = { module = "gov.ca.dwr.deltamodeling:calsurrogate"}
xaoptimizer = { module = "com.sunsetsoft.xa:xaoptimizer"}
gurobi = { module = "gurobi:gurobi"}

cb-dll = { module = "dwr.win.x64:cb", version.ref = "x64-dll" }
jep-dll = { module = "dwr.win.x64:jep", version.ref = "x64-dll" }
jhdf-dll = { module = "dwr.win.x64:jhdf", version.ref = "x64-dll" }
jhdf5-dll = { module = "dwr.win.x64:jhdf5", version.ref = "x64-dll" }

eclipse-core-runtime = { module = "org.eclipse.platform:org.eclipse.core.runtime", version.ref = "eclipse-core" }
eclipse-swt = { module = "org.eclipse.platform:org.eclipse.swt.win32.win32.x86_64", version.ref = "eclipse-swt"}
eclipse-compare = { module = "org.eclipse.platform:org.eclipse.compare", version.ref = "eclipse-compare" }
eclipse-ui = { module = "org.eclipse.platform:org.eclipse.ui", version.ref = "eclipse-ui" }
eclipse-jface = { module = "org.eclipse.platform:org.eclipse.jface", version.ref = "eclipse-jface" }
eclipse-jface-text = { module = "org.eclipse.platform:org.eclipse.jface.text", version.ref = "eclipse-jface-text" }
eclipse-debug-core = { module = "org.eclipse.platform:org.eclipse.debug.core", version.ref = "eclipse-debug-core" }
eclipse-debug-ui = { module = "org.eclipse.platform:org.eclipse.debug.ui", version.ref = "eclipse-debug-ui" }
eclipse-datatools-connectivity = { module = "org.eclipse.birt.dependencies:org.eclipse.datatools.connectivity", version.ref = "eclipse-datatools-connectivity" }
eclipse-osgi = { module = "org.eclipse.platform:org.eclipse.osgi", version.ref = "eclipse-osgi" }
eclipse-core-resources = { module = "org.eclipse.platform:org.eclipse.core.resources", version.ref = "eclipse-core-resources" }
eclipse-ui-views = { module = "org.eclipse.platform:org.eclipse.ui.views", version.ref = "eclipse-ui-views" }
eclipse-search = { module = "org.eclipse.platform:org.eclipse.search", version.ref = "eclipse-search" }
eclipse-xtext = { module = "org.eclipse.xtext:org.eclipse.xtext", version.ref = "eclipse-xtext" }
eclipse-xtext-ui-shared = { module = "org.eclipse.xtext:org.eclipse.xtext.ui.shared", version.ref = "eclipse-xtext" }
eclipse-xtext-ui-codetemplates = { module = "org.eclipse.xtext:org.eclipse.xtext.ui.codetemplates", version.ref = "eclipse-xtext" }
eclipse-xtext-ui-codetemplates-ui = { module = "org.eclipse.xtext:org.eclipse.xtext.ui.codetemplates.ui", version.ref = "eclipse-xtext" }
eclipse-xtext-common-types = { module = "org.eclipse.xtext:org.eclipse.xtext.common.types", version.ref = "eclipse-xtext" }
eclipse-xtext-common-types-ui = { module = "org.eclipse.xtext:org.eclipse.xtext.common.types.ui", version.ref = "eclipse-xtext" }
eclipse-xtext-builder = { module = "org.eclipse.xtext:org.eclipse.xtext.builder", version.ref = "eclipse-xtext" }
eclipse-emf-ecore = { module = "org.eclipse.emf:org.eclipse.emf.ecore", version.ref = "eclipse-xtext" }
eclipse-emf-edit = { module = "org.eclipse.emf:org.eclipse.emf.edit", version.ref = "eclipse-emf-edit" }
eclipse-emf-edit-ui = { module = "org.eclipse:org.eclipse.emf.edit.ui", version.ref = "eclipse-emf-edit-ui" }
eclipse-xtext-ui = { module = "org.eclipse.xtext:org.eclipse.xtext.ui", version.ref = "eclipse-xtext-ui" }
eclipse-ltk-core-refactoring = { module = "org.eclipse.platform:org.eclipse.ltk.core.refactoring", version.ref = "eclipse-ltk-core-refactoring" }

jaxb-api = { module = 'javax.xml.bind:jaxb-api', version.ref = "jaxb-api" }
jaxb-core = { module = 'com.sun.xml.bind:jaxb-core', version.ref = "jaxb-core" }
jaxb-impl = { module = 'com.sun.xml.bind:jaxb-impl', version.ref = "jaxb-impl" }
javax-activation = { module = 'javax.activation:activation', version.ref = "javax-activation" }

[bundles]
junit5 = [ "junit-5-engine", "junit-5-api", "junit-5-params" ]
