/*
 * generated by Xtext
 */
package gov.ca.water.wresl.xtext.editor.validation;

import gov.ca.water.wresl.xtext.editor.wreslEditor.WreslEditorPackage;
import java.util.ArrayList;
import java.util.List;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.xtext.validation.ComposedChecks;

@ComposedChecks(validators= {org.eclipse.xtext.validation.ImportUriValidator.class})
public class AbstractWreslEditorJavaValidator extends org.eclipse.xtext.validation.AbstractDeclarativeValidator {

	@Override
	protected List<EPackage> getEPackages() {
	    List<EPackage> result = new ArrayList<EPackage>();
	    result.add(WreslEditorPackage.eINSTANCE);
		return result;
	}

}
