#     Name: ParallelStudyTab.py
#   Author: Hao Xie
#   E-mail: hxie@water.ca.gov
#    Phone: 916.653.1072
# Last Rev: 2024.11.06 - zachary.roy@water.ca.gov
#  Purpose: Parallel StudyTab

# python modules
import shutil
import os
import Queue
import subprocess
import threading

#CalsimWsiDi class imports
from ParallelWsiDiGen import *

# java class imports - standard
from java.io import File

tab = "   "

# StudyTab class
class StudyTab:

   # constructor: initialize class parameters
   def __init__(self):

      # assign other class variables
      self.report = True

      #These are user options found in the WRIMS GUI.
      self.hideWarnings = True
      self.hideProgressDetails = False
      self.isLoading = False

   ### FUNCTIONS

   # function to run CALSIM
   def execute(self, engineName, k):
      print tab+ "Running Model "+str(k+1)+"\n"
   
      return subprocess.call(["cmd.exe", "/d", "/c", "call", engineName])

   # run WSI-DI procedure for each study
   def runForWsiStudy(self,k,numRun,wd,studyDvNames,crvName,lookupNames,engineNames,launchNames):
      print "Generate WSIDI for Study " + str(k+1)+"\n"
      for i in range(0,numRun):
         print "Start iteration " + str(i+1)+"\n"

         # save initial wsi-di tables.  Table will be appended with "_0" if it's the first guess.  "_1" if it's the first curve generated by WSI-DI and so on.
         for j in range(len(crvName)):
            tblName = lookupNames[k] + File.separator + "wsi_di_" + wd[j+k*len(crvName)].name.lower() + ".table"
            if (File(tblName).exists()):
               tblNameSave = tblName[:-6] + "_"+str(i)+tblName[-6:]
               shutil.copy(tblName,tblNameSave) #copy file

         # run CALSIM and check status
         status = self.execute(engineNames[k], k)
         if status != 0:
            raise RuntimeError("WRIMS model failed for study %d, iteration %d, exit code %d" %
                               (k + 1, i + 1, status))

         # load wsi-di data and fit curve
         for j in range(len(crvName)):
            wd[j+k*len(crvName)].load(studyDvNames[k])
            wd[j+k*len(crvName)].execute()

         print ""
         
         # save DSS as separate file name.  The DV file name is appended with the same integer as the WSI-DI curves upon which they depended.
         # For instance, the initial WSI-DI curves are saved as "_0".  The first iteration DV file is also labeled "_0".
         studyDvName=studyDvNames[k]
         if (i<numRun-1):
            dvNameSave = studyDvName[:-4] + "_"+str(i)+studyDvName[-4:]
            shutil.copy(studyDvName,dvNameSave) #copy file

   # run WSI-DI procedure
   def runForWsi(self,studyDvNames,crvName,crvWsiVar,crvDiVar,crvMax,lookupNames,engineNames,launchNames,offsets):

      print "Set parameters"

      newPath = os.path.join('..','')
      os.chdir(newPath)

      # number of Calsim runs needed (convergence)
      numRun = 3

      # establish variable for WsiDiGenerator (WRIMS java class)
      wd = []

      # instantiate WsiDiGenerator for each curve to be generated.
      for k in range(len(studyDvNames)):
         for i in range(len(crvName)):
            wd.append(WsiDiGenCl(crvName[i],crvWsiVar[i],crvDiVar[i],crvMax[i],studyDvNames[k],lookupNames[k],launchNames[k],offsets[k]))

      print "finished set parameters"
      
      # run CALSIM and extract wsi-di data points for curve generation
      errors = Queue.Queue()
      threads = []
      def runStudy(k):
         try:
            self.runForWsiStudy(k,numRun,wd,studyDvNames,crvName,lookupNames,engineNames,launchNames)
         except Exception as error:
            errors.put((k, error))
      for k in range(len(studyDvNames)):
         t = threading.Thread(target=runStudy, args=(k,))
         threads.append(t)
         t.start()
      for t in threads:
         t.join()
      failures = []
      while not errors.empty():
         failures.append(errors.get())
      if failures:
         failures.sort(key=lambda failure: failure[0])
         messages = ["study %d: %s" % (failure[0] + 1, str(failure[1])) for failure in failures]
         raise RuntimeError("One or more WsiDi studies failed: " + "; ".join(messages))
