plugins{
    id 'library.deps-conventions'
    id 'library.java-conventions'

    // The following plugin is used to build the OSGI bundle
    id 'biz.aQute.bnd.builder' version '7.2.3'
}

dependencies {

    //module dependencies
    implementation project(':third-party')
    implementation project(':wrims-ide')

    implementation(libs.eclipse.swt) {
        exclude group: "org.eclipse.platform", module: "org.eclipse.swt"
    }
    implementation(libs.eclipse.ui) {
        exclude group: "org.eclipse.platform", module: "org.eclipse.swt"
    }
    implementation(libs.eclipse.jface) {
        exclude group: "org.eclipse.platform", module: "org.eclipse.swt"
    }
    implementation libs.eclipse.osgi
    implementation libs.eclipse.core.resources
}

