/*
 * generated by Xtext
 */
package gov.ca.water.wresl.xtext.editor.parser.antlr;

import com.google.inject.Inject;
import gov.ca.water.wresl.xtext.editor.parser.antlr.internal.InternalWreslEditorParser;
import gov.ca.water.wresl.xtext.editor.services.WreslEditorGrammarAccess;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;

public class WreslEditorParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private WreslEditorGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected InternalWreslEditorParser createParser(XtextTokenStream stream) {
		return new InternalWreslEditorParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "WreslEvaluator";
	}
	
	public WreslEditorGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(WreslEditorGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
