name: SonarCloud Scan
on:
  workflow_run:
    workflows: ["Java CI"]
    type: [completed]
env:
  DEP_TOKEN: ${{ secrets.WRIMS_ENGINE_DEPENDENCIES_TOKEN }}

jobs:
  Sonar:
    name: SonarCloud Scanner
    runs-on: windows-2022
    if: (github.event_name == 'workflow_run' && github.event.workflow_run.conclusion == 'success') || github.event_name == 'push'
    steps:
      - name: Checkout PR
        uses: actions/checkout@v6
        env:
          REPO: ${{ github.event.workflow_run.head_repository.full_name }}
          REF: ${{ github.event.workflow_run.head_branch }}
        with:
          repository: ${{ env.REPO }}
          ref: ${{ env.REF }}
          fetch-depth:
            0
      - name: Verify token access to wrims-engine-dependencies
        shell: bash
        run: |
          curl --fail -i -u dwr-wrims-build:$DEP_TOKEN \
            https://maven.pkg.github.com/CentralValleyModeling/wrims-engine-dependencies/com.google.ortools/linearsolver/2013-01-10/linearsolver-2013-01-10.jar
      - name: Set up JDK 21
        uses: actions/setup-java@v5
        with:
          java-version: '21'
          distribution: 'temurin'
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v5
      - name: Cache SonarCloud packages
        uses: actions/cache@v5
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar
      - name: Download test + coverage reports from Java CI run
        uses: actions/download-artifact@v4
        with:
          name: coverage
          path: .
          run-id: ${{ github.event.workflow_run.id }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Build with Gradle
        shell: bash
        run: |
          ./gradlew build -x test -PcvmUserId="dwr-wrims-build" -PcvmPassword="$DEP_TOKEN"
      - name: Analyze Workflow Run
        shell: bash
        if: github.event_name == 'workflow_run'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          REVISION: ${{ github.event.workflow_run.head_sha }}
          REQUEST_NUM: ${{ github.event.workflow_run.pull_requests[0].number }}
          REQUEST_BRANCH: ${{ github.event.workflow_run.pull_requests[0].head.ref }}
          BASE_BRANCH: ${{ github.event.workflow_run.pull_requests[0].base.ref }}
        run: |
          ./gradlew sonar \
                  -PcvmUserId="dwr-wrims-build" \
                  -PcvmPassword="$DEP_TOKEN" \
                  --info \
                  "-Dsonar.scm.revision=$REVISION" \
                  "-Dsonar.pullrequest.key=$REQUEST_NUM" \
                  "-Dsonar.pullrequest.branch=$REQUEST_BRANCH" \
                  "-Dsonar.pullrequest.base=$BASE_BRANCH"
      - name: Analyze Push to Main
        shell: bash
        if: github.event_name == 'push'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          REVISION: ${{ github.sha }}
        run: |
          ./gradlew sonar \
                  -PcvmUserId="dwr-wrims-build" \
                  -PcvmPassword="$DEP_TOKEN" \
                  --info \
                  "-Dsonar.scm.revision=$REVISION"